name: Lint and Validate

on:
  push:
    branches:
      - '!master'
  pull_request:
    branches:
      - master

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: Terraform fmt
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.4
          terraform_wrapper: false

      - name: Terraform fmt
        run: terraform fmt -check -diff -recursive

  validate:
    runs-on: ubuntu-latest
    name: Terraform Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.4
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init

      - name: Validate Module
        env:
          AWS_REGION: 'eu-west-1'
        run: terraform validate

      - name: Validate Examples
        run: |
          for example in $(find examples -maxdepth 1 -mindepth 1 -type d); do
            cd ${example}
            terraform init
            terraform validate
            cd -
          done
